### ISSUE TITLE
Can not run in Angular 11

### ISSUE THREAD

**Issue by LucasDshg** [lucono/karma-test-explorer#77]
I just installed and tried to run an recived a error:
PS: The command ng test is working great. 
![image](https://user-images.githubusercontent.com/46797018/236524175-4630bc3f-36fe-416c-aa85-fad0412e49be.png)

Can not load "KarmaTestExplorerReporter"!
 TypeError [ERR_WORKER_UNSUPPORTED_EXTENSION]: The worker script extension must be ".js" or ".mjs". Received ".cjs"

Log Karma Server:

------------------------------------
Karma Test Explorer: Launching Karma
------------------------------------

05 05 2023 14:01:41.085:WARN [karma-server]: Passing raw CLI options to `new Server(config, done)` is deprecated. Use `parseConfig(configFilePath, cliOptions, {promiseConfig: true, throwErrors: true})` to prepare a processed `Config` instance and pass that as the `config` argument instead.

[2023-05-05 17:01:41.105] [DEBUG] [KarmaConfigLoader]: Loading Karma config: C:/Users/lucas.gomes/Documents/repos/bs-workspace/projects/corretor-lib/karma.conf.js

[2023-05-05 17:01:41.314] [DEBUG] [KarmaConfigLoader]: Using custom launcher: {
  "base": "Chrome",
  "flags": [
    "--headless",
    "--disable-gpu",
    "--disable-dev-shm-usage",
    "--remote-debugging-port=9222"
  ]
}

05 05 2023 14:01:45.379:ERROR [reporter]: Can not load "KarmaTestExplorerReporter"!
 TypeError [ERR_WORKER_UNSUPPORTED_EXTENSION]: The worker script extension must be ".js" or ".mjs". Received ".cjs"
    at new Worker (internal/worker.js:85:15)
    at Pe.KarmaTestExplorerReporter (C:\Users\lucas.gomes\.vscode\extensions\lucono.karma-test-explorer-0.8.2\dist\karma.conf.cjs:1:109835)
    at invoke (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\di\lib\injector.js:75:15)
    at Array.instantiate (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\di\lib\injector.js:59:20)
    at Injector.get (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\di\lib\injector.js:48:43)
    at C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\karma\lib\reporter.js:118:75
    at Array.forEach (<anonymous>)
    at createReporters (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\karma\lib\reporter.js:100:9)
    at Array.invoke (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\di\lib\injector.js:75:15)
    at get (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\di\lib\injector.js:48:43)
    at C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\di\lib\injector.js:71:14
    at Array.map (<anonymous>)
    at Injector.invoke (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\di\lib\injector.js:70:31)
    at createWebServer (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\karma\lib\web-server.js:74:24)
    at Array.invoke (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\di\lib\injector.js:75:15)
    at Injector.get (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\di\lib\injector.js:48:43)
    at Server._start (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\karma\lib\server.js:215:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Server.start (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\karma\lib\server.js:155:7)

05 05 2023 14:01:45.399:WARN [karma]: No captured browser, open http://localhost:9976/

05 05 2023 14:01:45.401:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9976/
05 05 2023 14:01:45.402:INFO [launcher]: Launching browsers KarmaTestExplorer_CustomLauncher with concurrency unlimited

05 05 2023 14:01:45.402:ERROR [karma-server]: Error: Found 1 load error
    at Server.<anonymous> (C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\karma\lib\server.js:243:26)
    at Object.onceWrapper (events.js:298:28)
    at Server.emit (events.js:214:15)
    at emitListeningNT (net.js:1332:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)

Log Test Explorer:

[2023-05-05 17:08:30.977] [INFO] [Adapter]: Resetting adapter
[2023-05-05 17:08:30.977] [DEBUG] [KarmaTestExplorer]: Test operation cancellation requested - Aborting any currently running test operation
[2023-05-05 17:08:30.977] [DEBUG] [DefaultTestManager]: Stopping test manager
[2023-05-05 17:08:30.977] [DEBUG] [DefaultTestManager]: Karma event listener is already stopped
[2023-05-05 17:08:30.977] [DEBUG] [DefaultTestManager]: Karma server is already stopped
[2023-05-05 17:08:30.977] [DEBUG] [DefaultTestManager]: Stopped test manager
[2023-05-05 17:08:30.978] [DEBUG] [DefaultTestManager]: Stopping test manager
[2023-05-05 17:08:30.979] [DEBUG] [DefaultTestManager]: Karma event listener is already stopped
[2023-05-05 17:08:30.979] [DEBUG] [DefaultTestManager]: Karma server is already stopped
[2023-05-05 17:08:30.979] [DEBUG] [DefaultTestManager]: Stopped test manager
[2023-05-05 17:08:30.982] [DEBUG] [Adapter]: Assembling new test explorer
[2023-05-05 17:08:30.982] [DEBUG] [Adapter]: Re/creating test explorer with extension configuration: {
  "logger": {
    "loggerName": "ExtensionConfig",
    "appender": {
      "outputChannelName": "Karma Test Explorer (bs-workspace: corretor-lib)",
      "options": {
        "enabled": true,
        "lazyCreate": false
      },
      "outputChannel": {
        "name": "Karma Test Explorer (bs-workspace: corretor-lib)"
      }
    },
    "logLevel": "debug"
  },
  "projectType": "angular",
  "projectName": "corretor-lib",
  "projectPath": "C:/Users/lucas.gomes/Documents/repos/bs-workspace/projects/corretor-lib",
  "projectInstallRootPath": "C:/Users/lucas.gomes/Documents/repos/bs-workspace",
  "projectKarmaConfigFilePath": "C:/Users/lucas.gomes/Documents/repos/bs-workspace/projects/corretor-lib/karma.conf.js",
  "baseKarmaConfFilePath": "C:/Users/lucas.gomes/.vscode/extensions/lucono.karma-test-explorer-0.8.2/dist/karma.conf.cjs",
  "karmaPort": 9976,
  "testTriggerMethod": "http",
  "testParsingMethod": "ast",
  "failOnStandardError": false,
  "defaultSocketConnectionPort": 9999,
  "logLevel": "debug",
  "karmaLogLevel": "info",
  "karmaReporterLogLevel": "disable",
  "autoWatchEnabled": true,
  "karmaReadyTimeout": 900000,
  "testGrouping": "folder",
  "flattenSingleChildFolders": true,
  "environment": {},
  "envExclude": [],
  "reloadOnKarmaConfigChange": true,
  "customLauncher": {
    "base": "Chrome",
    "flags": [
      "--headless",
      "--disable-gpu",
      "--disable-dev-shm-usage",
      "--remote-debugging-port=9222"
    ]
  },
  "testFiles": [
    "**/*{.,-,_}{test,spec}.{ts,js}",
    "**/{test,spec}{.,-,_}*.{ts,js}"
  ],
  "allowGlobalPackageFallback": true,
  "excludeDisabledTests": false,
  "showOnlyFocusedTests": false,
  "showUnmappedTests": true,
  "showTestDefinitionTypeIndicators": true,
  "debuggerConfig": {
    "name": "Karma Test Explorer Debugging",
    "type": "chrome",
    "request": "attach",
    "browserAttachLocation": "workspace",
    "address": "localhost",
    "port": 9222,
    "timeout": 60000,
    "webRoot": "C:/Users/lucas.gomes/Documents/repos/bs-workspace"
  },
  "reloadOnChangedFiles": [],
  "defaultDebugPort": 9222,
  "excludeFiles": [
    "**/node_modules/**/*"
  ]
}
[2023-05-05 17:08:30.982] [DEBUG] [Adapter]: Creating main factory
[2023-05-05 17:08:30.982] [DEBUG] [MainFactory]: Detecting test framework from karma config file: C:/Users/lucas.gomes/Documents/repos/bs-workspace/projects/corretor-lib/karma.conf.js
[2023-05-05 17:08:30.982] [DEBUG] [SimpleFileHandler]: Reading file synchronously: C:/Users/lucas.gomes/Documents/repos/bs-workspace/projects/corretor-lib/karma.conf.js
[2023-05-05 17:08:30.982] [DEBUG] [MainFactory]: Detected frameworks from karma config: jasmine, @angular-devkit/build-angular
[2023-05-05 17:08:30.982] [DEBUG] [MainFactory]: Detected test framework: jasmine
[2023-05-05 17:08:30.982] [INFO] [MainFactory]: Using test framework: jasmine (auto-detected)
[2023-05-05 17:08:30.982] [DEBUG] [MainFactory]: Creating test helper
[2023-05-05 17:08:30.982] [DEBUG] [MainFactory]: Creating process handler
[2023-05-05 17:08:30.982] [DEBUG] [MainFactory]: Creating test locator
[2023-05-05 17:08:30.982] [DEBUG] [MainFactory]: Creating AST test definition provider
[2023-05-05 17:08:30.982] [DEBUG] [MainFactory]: Creating test store
[2023-05-05 17:08:30.982] [DEBUG] [Adapter]: Getting process handler from factory
[2023-05-05 17:08:30.983] [DEBUG] [Adapter]: Getting test locator from factory
[2023-05-05 17:08:30.983] [DEBUG] [Adapter]: Getting test store from factory
[2023-05-05 17:08:30.983] [DEBUG] [Adapter]: Getting test manager from factory
[2023-05-05 17:08:30.983] [DEBUG] [AngularFactory]: Creating Angular test server executor
[2023-05-05 17:08:30.983] [INFO] [AngularFactory]: Using Angular project 'corretor-lib' at root path 'C:/Users/lucas.gomes/Documents/repos/bs-workspace/projects/corretor-lib' and karma config file 'C:/Users/lucas.gomes/Documents/repos/bs-workspace/projects/corretor-lib/karma.conf.js'
[2023-05-05 17:08:30.983] [DEBUG] [KarmaFactory]: Creating Karma http test run executor
[2023-05-05 17:08:30.983] [DEBUG] [Adapter]: Getting file watcher from factory
[2023-05-05 17:08:30.983] [DEBUG] [FileWatcher]: Creating file watchers for monitored files
[2023-05-05 17:08:30.983] [DEBUG] [FileWatcher]: Registering file handler for files: [
  "karma.conf.js"
]
[2023-05-05 17:08:30.983] [DEBUG] [FileWatcher]: Creating file watcher for file or pattern 'karma.conf.js' using base path: c:\Users\lucas.gomes\Documents\repos\bs-workspace
[2023-05-05 17:08:30.983] [DEBUG] [FileWatcher]: Creating file watchers for test file changes
[2023-05-05 17:08:30.983] [DEBUG] [FileWatcher]: Registering file handler for files: [
  "**/*{.,-,_}{test,spec}.{ts,js}",
  "**/{test,spec}{.,-,_}*.{ts,js}"
]
[2023-05-05 17:08:30.983] [DEBUG] [FileWatcher]: Creating file watcher for file or pattern '**/*{.,-,_}{test,spec}.{ts,js}' using base path: c:\Users\lucas.gomes\Documents\repos\bs-workspace
[2023-05-05 17:08:30.983] [DEBUG] [FileWatcher]: Creating file watcher for file or pattern '**/{test,spec}{.,-,_}*.{ts,js}' using base path: c:\Users\lucas.gomes\Documents\repos\bs-workspace
[2023-05-05 17:08:30.983] [DEBUG] [Adapter]: Creating test explorer
[2023-05-05 17:08:30.983] [DEBUG] [KarmaTestExplorer]: Test load started
[2023-05-05 17:08:30.983] [DEBUG] [KarmaTestExplorer]: Test hard refresh started
[2023-05-05 17:08:30.983] [DEBUG] [TestLocator]: Refresh requested for all spec file(s): ["**/*{.,-,_}{test,spec}.{ts,js}","**/{test,spec}{.,-,_}*.{ts,js}"]
[2023-05-05 17:08:30.983] [DEBUG] [TestLocator]: No refresh currently in progress - will commence new refresh for files: ["**/*{.,-,_}{test,spec}.{ts,js}","**/{test,spec}{.,-,_}*.{ts,js}"]
[2023-05-05 17:08:30.983] [DEBUG] [TestLocator]: Refreshing all spec file(s): ["**/*{.,-,_}{test,spec}.{ts,js}","**/{test,spec}{.,-,_}*.{ts,js}"]
[2023-05-05 17:08:30.985] [DEBUG] [KarmaTestExplorer]: Refresh request - Test manager is not started - Starting it
[2023-05-05 17:08:31.000] [DEBUG] [PortAcquisitionClient]: Request for 1 port(s) at base port 9976 acquired: 9976
[2023-05-05 17:08:31.000] [INFO] [DefaultTestManager]: Using requested --> available karma port: 9976 --> 9976
[2023-05-05 17:08:31.247] [DEBUG] [PortAcquisitionClient]: Request for 1 port(s) at base port 9999 acquired: 10022
[2023-05-05 17:08:31.247] [INFO] [DefaultTestManager]: Using requested --> available karma listener socket port: 9999 --> 10022
[2023-05-05 17:08:31.258] [DEBUG] [PortAcquisitionClient]: Request for 1 port(s) at base port 9222 acquired: 9222
[2023-05-05 17:08:31.258] [INFO] [DefaultTestManager]: Using requested --> available debug port: 9222 --> 9222
[2023-05-05 17:08:31.258] [DEBUG] [KarmaTestListener]: Attempting to listen on port 10022
[2023-05-05 17:08:31.259] [INFO] [KarmaTestServer]: Starting karma server
[2023-05-05 17:08:31.260] [DEBUG] [AngularTestServerExecutor]: Executing server start with karma port '9976' and karma socket port '10022'
[2023-05-05 17:08:31.276] [DEBUG] [AngularTestServerExecutor]: Found '@angular/cli' module at: C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\@angular\cli
[2023-05-05 17:08:31.276] [DEBUG] [AngularTestServerExecutor::SimpleProcess]: Process amc0ipf0oxv: 
Executing command: 'C:\Program Files\nodejs\node.EXE' 
with args: ["C:\\Users\\lucas.gomes\\Documents\\repos\\bs-workspace\\node_modules\\@angular\\cli\\bin\\ng","test","corretor-lib","--karma-config=C:/Users/lucas.gomes/.vscode/extensions/lucono.karma-test-explorer-0.8.2/dist/karma.conf.cjs","--progress=false","--no-watch"]
[2023-05-05 17:08:31.282] [DEBUG] [AngularTestServerExecutor::SimpleProcess]: Process amc0ipf0oxv - process spawned successfully with PID 21104 for command: C:\Program Files\nodejs\node.EXE C:\Users\lucas.gomes\Documents\repos\bs-workspace\node_modules\@angular\cli\bin\ng test corretor-lib --karma-config=C:/Users/lucas.gomes/.vscode/extensions/lucono.karma-test-explorer-0.8.2/dist/karma.conf.cjs --progress=false --no-watch
[2023-05-05 17:08:31.284] [INFO] [KarmaTestListener]: Waiting for Karma to connect on port 10022
[2023-05-05 17:08:31.330] [DEBUG] [SimpleFileHandler]: Resolved 2 file(s) from file patterns: ["**/*{.,-,_}{test,spec}.{ts,js}","**/{test,spec}{.,-,_}*.{ts,js}"]
[2023-05-05 17:08:31.330] [DEBUG] [TestLocator]: Requested --> filtered file count to refresh: 2 --> 2
[2023-05-05 17:08:31.330] [DEBUG] [SimpleFileHandler]: Reading file async: C:/Users/lucas.gomes/Documents/repos/bs-workspace/projects/corretor-lib/src/lib/services/data-power/data-power-private.service.spec.ts
[2023-05-05 17:08:31.334] [DEBUG] [AstTestFileParser]: Parse operation e0xspcpymed: Parsed 2 total tests from file 'C:/Users/lucas.gomes/Documents/repos/bs-workspace/projects/corretor-lib/src/lib/services/data-power/data-power-private.service.spec.ts' in 0.00 secs
[2023-05-05 17:08:31.334] [DEBUG] [SimpleFileHandler]: Reading file async: C:/Users/lucas.gomes/Documents/repos/bs-workspace/projects/corretor-lib/src/lib/services/data-power/data-power-protected.service.spec.ts
[2023-05-05 17:08:31.336] [DEBUG] [AstTestFileParser]: Parse operation ok2i6ahtlk9: Parsed 2 total tests from file 'C:/Users/lucas.gomes/Documents/repos/bs-workspace/projects/corretor-lib/src/lib/services/data-power/data-power-protected.service.spec.ts' in 0.00 secs
[2023-05-05 17:08:31.336] [DEBUG] [TestLocator]: Refreshed 2 spec files from glob list in 0.35 secs: ["**/*{.,-,_}{test,spec}.{ts,js}","**/{test,spec}{.,-,_}*.{ts,js}"]

Package.json
```JSON
{
  "name": "bs-workspace",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.2.14",
    "@angular/common": "~11.2.14",
    "@angular/compiler": "~11.2.14",
    "@angular/core": "~11.2.14",
    "@angular/forms": "~11.2.14",
    "@angular/platform-browser": "~11.2.14",
    "@angular/platform-browser-dynamic": "~11.2.14",
    "@angular/router": "~11.2.14",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.18",
    "@angular/cli": "~11.2.19",
    "@angular/compiler-cli": "~11.2.14",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "jwt-decode": "^3.1.2",
    "karma": "^6.4.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.5.0",
    "ng-packagr": "^11.0.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  }
}
```

```Javascript
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      jasmine: {
        // you can add configuration options for Jasmine here
        // the possible options are listed at https://jasmine.github.io/api/edge/Configuration.html
        // for example, you can disable the random execution with `random: false`
        // or set a specific seed with `seed: 4321`
      },
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    jasmineHtmlReporter: {
      suppressAll: true // removes the duplicated traces
    },
    coverageReporter: {
      dir: require('path').join(__dirname, '../../coverage/corretor'),
      subdir: '.',
      reporters: [
        { type: 'html' },
        { type: 'text-summary' }
      ]
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    restartOnFileChange: true,
  });
};
````

**Please Provide the Following Information**
 
 - OS and Version: Win 10
 - Node Version: 12.10.0
 - VS Code Version:  1.78.0

**Comment by LucasDshg** [comment]
Fixed update node to 14
